# Collector specific configuration
base_url: "https://goadmin.ifrc.org/api/v2/"
get_params: "/?limit=50000&format="

appeal:
  url_path: "appeal"
  download_path: "appeals.csv"
  heading: "Appeals"
  tags:
    - "aid funding"
  hxltags:
    "aid": "#meta+id"
    "name": "#crisis+name"
    "dtype.id": "#cause+id"
    "dtype.name": "#cause+name"
    "atype": "#meta+appeal+type"
    "status": "#status"
    "code": "#meta+appeal+id"
    "sector": "#region+name+office"
    "num_beneficiaries": "#beneficiaries+num"
    "amount_requested": "#value+requested"
    "amount_funded": "#value+funded"
    "start_date": "#date+start"
    "end_date": "#date+end"
    "country.iso3": "#country+code"
    "country.name": "#country+name"
    "country.society_name": "#org+national_society"
    "region.id": "#region+id"
    "region.region_name": "#region+name"

whowhatwhere:
  url_path: "project"
  download_path: "whowhatwhere.json"
  heading: "3W"
  tags:
    - "who is doing what and where - 3w - 4w - 5w"
  hxltags:
    "country.iso3": "#country+code"
    "country.name": "#country+name"
    "district.name": "#adm1+code"
    "country.society_name": "#org+national_society"
    "primary_sector": "#sector+primary"
    "secondary_sectors": "#sector+secondary"
    "programme_type": "#activity+type"
    "operation_type": "#operations+type"
    "status": "#status"
    "start_date": "#date+start"
    "end_date": "#date+end"
    "budget_amount": "#value+budget"
    "actual_expenditure": "#value+spent"
    "target_male": "#targeted+m"
    "target_female": "#targeted+f"
    "target_other": "#targeted+other"
    "target_total": "#targeted+total"
    "reached_male": "#reached+m"
    "reached_female": "#reached+f"
    "reached_other": "#reached+other"
    "reached_total": "#reached+total"
    "name": "#activity"
