# Collector specific configuration
base_url: "https://goadmin.ifrc.org/api/v2/"
get_params: "/?limit=200&format=json"

countries:
  url_path: "country"
  filename: "countries_{index}.json"

appeals:
  publish: True
  url_path: "appeal"
  additional_params: "&appeal__real_data_update__gte="
  filename: "appeals_{index}.json"
  heading: "Appeals"
  tags:
    - "funding"
  hxltags:
    "aid": "#meta+id"
    "name": "#crisis+name"
    "dtype.id": "#cause+id"
    "dtype.name": "#cause+name"
    "atype": "#meta+appeal+type"
    "status": "#status+code"
    "status_display": "#status+name"
    "code": "#meta+appeal+id"
    "sector": "#region+name+office"
    "initial_num_beneficiaries": "#beneficiaries+num"
    "amount_requested": "#value+funding+required+chf"
    "amount_funded": "#value+funding+total+chf"
    "start_date": "#date+start"
    "end_date": "#date+end"
    "country.iso3": "#country+code"
    "country.name": "#country+name"
    "country.society_name": "#org+national_society"
    "region.id": "#region+id"
    "region.region_name": "#region+name"
  showcase_urls:
    global: "https://go.ifrc.org/"
  quickcharts_hxltags:
    "Year": "#date+year"
    "Year Month": "#date+yearmonth"
    "Last Year": "#meta+lastyear"
    "Appeal Type": "#meta+appeal+type"
    "Number of Appeals": "#indicator+appeal+num"
    "Funded": "#value+funding+total+chf"
    "Beneficiaries": "#beneficiaries+num"

personnel:
  publish: True
  url_path: "personnel"
  additional_params: "&deployment__updated_at__gte="
  filename: "personnel_{index}.json"
  heading: "Personnel"
  tags:
    - "operational capacity"
  header_replacements:
    "deployment.country_deployed_to": "country_deployed_to"
    "deployment.region_deployed_to": "region_deployed_to"
    "deployment.event_deployed_to": "event_deployed_to"
  hxltags:
    "start_date": "#date+start"
    "end_date": "#date+end"
    "type": "#role+type"
    "country_from.iso": "#country+from+code+v_iso2"
    "country_from.iso3": "#country+from+code"
    "country_from.society_name": "#org+national_society+from"
    "country_from.name": "#country+from+name"
    "country_to.iso": "#country+to+code+v_iso2"
    "country_to.iso3": "#country+to+code"
    "country_to.society_name": "#org+national_society+to"
    "country_to.name": "#country+to+name"
    "country_deployed_to.iso": "#country+deployed+code+v_iso2"
    "country_deployed_to.iso3": "#country+deployed+code"
    "country_deployed_to.society_name": "#org+national_society+deployed"
    "country_deployed_to.name": "#country+deployed+name"
    "event_deployed_to.dtype.id": "#event+type+code"
    "event_deployed_to.dtype.name": "#event+type+name"
    "event_deployed_to.dtype.summary": "#event+type+decription"
    "event_deployed_to.countries.iso": "#country+event+code+v_iso2"
    "event_deployed_to.countries.iso3": "#country+event+code"
    "event_deployed_to.countries.society_name": "#org+national_society+event"
    "event_deployed_to.countries.name": "#country+event+name"
    "event_deployed_to.ifrc_severity_level": "#severity+code+ifrc"
    "event_deployed_to.ifrc_severity_level_display": "#severity+name+ifrc"
    "event_deployed_to.glide": "#event+code+v_glide"
    "event_deployed_to.disaster_start_date": "#date+disaster+start"
    "event_deployed_to.id": "#event+code+ifrc"
    "event_deployed_to.name": "#event+name"
    "is_active": "#status+active"
    "role": "#role+name"
  showcase_urls:
    global: "https://go.ifrc.org/deployments/overview/"
  quickcharts_hxltags:
    "Year": "#date+year"
    "Year Month": "#date+yearmonth"
    "Last Year": "#meta+lastyear"
    "Appeal Type": "#meta+appeal+type"
    "Number of Appeals": "#indicator+appeal+num"
    "Funded": "#value+funding+total+chf"
    "Beneficiaries": "#beneficiaries+num"

whowhatwhere:
  publish: False
  url_path: "project"
  additional_params: "&modified_at__gte="
  filename: "whowhatwhere_{index}.json"
  heading: "3W"
  tags:
    - "who is doing what and where-3w-4w-5w"
  hxltags:
    "country.iso3": "#country+code"
    "country.name": "#country+name"
    "district.names": "#adm1+names"
    "country.society_name": "#org+national_society"
    "primary_sector": "#sector+primary"
    "secondary_sectors": "#sector+secondary"
    "programme_type": "#activity+type"
    "operation_type": "#operations+type"
    "status_display": "#status+name"
    "start_date": "#date+start"
    "end_date": "#date+end"
    "budget_amount": "#value+budget"
    "actual_expenditure": "#value+spent"
    "target_male": "#targeted+m"
    "target_female": "#targeted+f"
    "target_other": "#targeted+other"
    "target_total": "#targeted+total"
    "reached_male": "#reached+m"
    "reached_female": "#reached+f"
    "reached_other": "#reached+other"
    "reached_total": "#reached+total"
    "name": "#activity"
  showcase_urls:
    global: "https://go.ifrc.org/three-w/"
    country: "https://go.ifrc.org/countries/{id}#3w"
