# Collector specific configuration
base_url: "https://goadmin.ifrc.org/api/v2/"
get_params: "/?limit=200&format=json"

countries:
  url_path: "country"
  filename: "countries_{index}.json"

appeals:
  publish: True
  url_path: "appeal"
  additional_params: "&appeal__real_data_update__gte="
  filename: "appeals_{index}.json"
  heading: "Appeals"
  tags:
    - "funding"
  hxltags:
    "aid": "#meta+id"
    "name": "#crisis+name"
    "dtype.id": "#cause+id"
    "dtype.name": "#cause+name"
    "atype": "#meta+appeal+type"
    "status": "#status+code"
    "status_display": "#status+name"
    "code": "#meta+appeal+id"
    "sector": "#region+name+office"
    "initial_num_beneficiaries": "#beneficiaries+num"
    "amount_requested": "#value+funding+required+chf"
    "amount_funded": "#value+funding+total+chf"
    "start_date": "#date+start"
    "end_date": "#date+end"
    "country.iso3": "#country+code"
    "country.name": "#country+name"
    "country.society_name": "#org+national_society"
    "region.id": "#region+id"
    "region.region_name": "#region+name"
  showcase_urls:
    global: "https://go.ifrc.org/"
  quickcharts_hxltags:
    "Year": "#date+year"
    "Year Month": "#date+yearmonth"
    "Last Year": "#meta+last_year"
    "DREF Appeals": "#indicator+appeal+dref+num"
    "Emergency Appeals": "#indicator+appeal+emergency+num"
    "Requested": "#value+funding+required+chf"
    "Funded": "#value+funding+total+chf"

whowhatwhere:
  publish: False
  url_path: "project"
  additional_params: "&modified_at__gte="
  filename: "whowhatwhere_{index}.json"
  heading: "3W"
  tags:
    - "who is doing what and where-3w-4w-5w"
  hxltags:
    "country.iso3": "#country+code"
    "country.name": "#country+name"
    "district.names": "#adm1+names"
    "country.society_name": "#org+national_society"
    "primary_sector": "#sector+primary"
    "secondary_sectors": "#sector+secondary"
    "programme_type": "#activity+type"
    "operation_type": "#operations+type"
    "status_display": "#status+name"
    "start_date": "#date+start"
    "end_date": "#date+end"
    "budget_amount": "#value+budget"
    "actual_expenditure": "#value+spent"
    "target_male": "#targeted+m"
    "target_female": "#targeted+f"
    "target_other": "#targeted+other"
    "target_total": "#targeted+total"
    "reached_male": "#reached+m"
    "reached_female": "#reached+f"
    "reached_other": "#reached+other"
    "reached_total": "#reached+total"
    "name": "#activity"
  showcase_urls:
    global: "https://go.ifrc.org/three-w/"
    country: "https://go.ifrc.org/countries/{id}#3w"
